# netlify.toml

# Правило 1: "Маскирует" главную страницу index.html
# Оно сработает, когда кто-то откроет /s/ или /s/?id=...
[[redirects]]
  from = "/s/"
  to = "https://olgo1.github.io/work/index.html"
  status = 200 # <-- "Маскировка" (Proxy)
  force = true 

# Правило 2: "Маскирует" ВСЕ остальные файлы (JS, CSS, картинки)
# Оно поймает /s/utils.js, /s/sheet_map.js, /s/sheets/4count0_sheet.js и т.д.
[[redirects]]
  from = "/s/*"
  to = "https://olgo1.github.io/work/:splat"
  status = 200 # <-- "Маскировка" (Proxy)
  force = true